### ISSUE TITLE
When setting IPV4 Address, error occurs

### ISSUE THREAD

**Issue by MichelePip** [Zerui18/XenLive-Issues-Tracker#2]
1 Device Information
Device Model - iPad8,,1
iOS Version - 14.3 RC
Tweak Version (you should be on the latest version!)
2 Expected Behaviour
What should happen.

The Devices IP address should be changed normally.

3 Current Behaviour
What did happen.

`XenLive Edit: Failed to sync with device: Error: Device IP not set!`

4 Steps to Reproduce
A short series of steps that reliably reproduces this issue.

Set the IP address to `192.168.0.158` and press enter.

5 Additional
Any additional information that'll be useful for debugging this issue?

**Comment by Zerui18** [comment]
That's ok. As long as you have entered the device IP, that message would not show anymore. The same goes for other fields in settings.
